### ISSUE TITLE
New file introduced yesterday didn't make it to gh-pages after a successful build

### ISSUE THREAD

**Issue by Kritner** [celic/acvp-metanorma#13]
PR #11 had a successful build when merged in, but the new html page didn't make it onto the gh-pages branch, not sure why yet.

**Comment by Kritner** [comment]
Ah glancing at the [make file](https://github.com/celic/acvp-metanorma/blob/master/Makefile) I guess that's why.  

I don't know much about make files, but i'm guessing we could do something like a directory search of the root directory (with no directory traversal) for .adoc and run against all of them yeah?

**Comment by celic** [comment]
Could do a directory search for all `*.adoc` files. At the time I had some I wanted built and some I didn't. List is the easiest.
